name: Maven CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the JDK version you need
          distribution: 'adopt'  # Options: 'adopt', 'zulu', 'temurin', etc.

      - name: Build with Maven
        run: mvn clean package

